# Generated by Django 3.2.20 on 2024-01-24 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0017_alter_transactions_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=100)),
                ('trn_no', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('trn_type', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('openingbalance', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('creditlimit', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('current_date', models.DateField(blank=True, max_length=255, null=True)),
                ('End_date', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalfield1', models.CharField(blank=True, max_length=100, null=True)),
                ('additionalfield2', models.CharField(blank=True, max_length=100, null=True)),
                ('additionalfield3', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_no', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('subtotal', models.IntegerField(default=0, null=True)),
                ('vat', models.CharField(default=0, max_length=100, null=True)),
                ('adjustment', models.CharField(default=0, max_length=100)),
                ('grandtotal', models.FloatField(default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.employee')),
                ('party', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(max_length=255)),
                ('trans_number', models.CharField(max_length=255)),
                ('trans_date', models.DateTimeField()),
                ('total', models.CharField(max_length=255)),
                ('balance', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company')),
                ('party', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('tax', models.CharField(blank=True, max_length=255, null=True)),
                ('totalamount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.employee')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.item')),
                ('salesinvoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.salesinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='PartyTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('transactiondate', models.DateField(auto_now=True)),
                ('Transactions_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.transactions_party')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company')),
                ('party', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
