# Generated by Django 3.2.20 on 2024-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0018_party_partytransactionhistory_salesinvoice_salesinvoiceitem_transactions_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='trn_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
