# Generated by Django 3.2.20 on 2024-01-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0019_transactions_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_party',
            name='trans_number',
            field=models.CharField(max_length=255),
        ),
    ]
