# Generated by Django 3.2.20 on 2024-03-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0020_auto_20240228_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='total_taxamount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
