# Generated by Django 3.2.20 on 2024-01-09 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0020_alter_transactions_party_trans_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_party',
            name='party',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party'),
        ),
    ]
