# Generated by Django 3.2.20 on 2024-03-06 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0021_salesinvoice_total_taxamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.item'),
        ),
    ]
