# Generated by Django 3.2.20 on 2024-01-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0021_alter_transactions_party_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='gst_no',
            new_name='trn_no',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='gst_type',
            new_name='trn_type',
        ),
        migrations.AlterField(
            model_name='transactions_party',
            name='balance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions_party',
            name='total',
            field=models.CharField(max_length=255),
        ),
    ]
