# Generated by Django 3.2.20 on 2024-03-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0022_salesinvoice_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='creditlimit',
        ),
        migrations.AddField(
            model_name='party',
            name='at_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='opening_stock',
            field=models.IntegerField(default=0),
        ),
    ]
