# Generated by Django 3.2.20 on 2024-03-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0024_auto_20240308_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='partystatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
