# Generated by Django 3.2.20 on 2024-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0024_partytransactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partytransactionhistory',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
